from typing import List
from scanner.base import BaseScanner
from scanner.models import Finding


class HardcodedSecretsScanner(BaseScanner):
    name = "HardcodedSecretsScanner"
    category = "Hardcoded Secrets"

    PATTERNS = [
        {
            "pattern": r'''(?i)(?:password|passwd|pwd)\s*[=:]\s*["'][^"']{3,}["']''',
            "vulnerability": "Hardcoded Password",
            "severity": "critical",
            "confidence": "high",
            "description": "A hardcoded password was found in the source code. Passwords in code can be extracted by anyone with access to the repository.",
            "remediation": "Store passwords in environment variables or a secrets manager (e.g., AWS Secrets Manager, HashiCorp Vault). Never commit passwords to source code.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)(?:api[_-]?key|apikey)\s*[=:]\s*["'][A-Za-z0-9_\-]{16,}["']''',
            "vulnerability": "Hardcoded API Key",
            "severity": "critical",
            "confidence": "high",
            "description": "A hardcoded API key was found in the source code. Exposed API keys can be used by attackers to access services and incur costs.",
            "remediation": "Store API keys in environment variables or a secrets manager. Use .env files (added to .gitignore) for local development.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)(?:secret|secret[_-]?key)\s*[=:]\s*["'][^"']{8,}["']''',
            "vulnerability": "Hardcoded Secret Key",
            "severity": "critical",
            "confidence": "high",
            "description": "A hardcoded secret key was found in the source code. Secret keys should never be stored in code.",
            "remediation": "Use environment variables or a dedicated secrets management service. Rotate the exposed secret immediately.",
            "owasp_ref": "A02:2021 - Cryptographic Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)AWS[_-]?(?:ACCESS[_-]?KEY[_-]?ID|SECRET[_-]?ACCESS[_-]?KEY)\s*[=:]\s*["']?[A-Za-z0-9/+=]{16,}''',
            "vulnerability": "AWS Credentials Exposed",
            "severity": "critical",
            "confidence": "high",
            "description": "AWS credentials found in source code. This gives attackers access to your AWS infrastructure and can lead to data breaches and financial loss.",
            "remediation": "Use IAM roles, AWS SSO, or environment variables. Never hardcode AWS credentials. Rotate exposed credentials immediately.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''AKIA[0-9A-Z]{16}''',
            "vulnerability": "AWS Access Key ID",
            "severity": "critical",
            "confidence": "high",
            "description": "An AWS Access Key ID was detected. This key format (AKIA...) is a real AWS credential that provides programmatic access to AWS services.",
            "remediation": "Remove the key immediately, rotate it in AWS IAM, and use IAM roles or environment variables instead.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)(?:token|auth[_-]?token|access[_-]?token)\s*[=:]\s*["'][A-Za-z0-9_\-\.]{20,}["']''',
            "vulnerability": "Hardcoded Token",
            "severity": "high",
            "confidence": "medium",
            "description": "A hardcoded authentication token was found. Tokens in source code can be extracted and misused.",
            "remediation": "Store tokens in environment variables or a secrets manager. Use short-lived tokens where possible.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''-----BEGIN (?:RSA |EC |DSA )?PRIVATE KEY-----''',
            "vulnerability": "Private Key in Source Code",
            "severity": "critical",
            "confidence": "high",
            "description": "A private key was found embedded in source code. Private keys must be kept secret and never committed to repositories.",
            "remediation": "Remove the private key from code immediately. Store keys in a secure key management system. Regenerate the key pair if this key was ever committed.",
            "owasp_ref": "A02:2021 - Cryptographic Failures",
            "cwe_id": "CWE-321",
        },
        {
            "pattern": r'''(?i)(?:database[_-]?url|db[_-]?pass|db[_-]?password|connection[_-]?string)\s*[=:]\s*["'][^"']{5,}["']''',
            "vulnerability": "Hardcoded Database Credentials",
            "severity": "critical",
            "confidence": "high",
            "description": "Database credentials found in source code. Exposed database credentials can lead to unauthorized data access.",
            "remediation": "Use environment variables for database credentials. Configure them through your deployment platform's secret management.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)mongodb(\+srv)?://[^:]+:[^@]+@''',
            "vulnerability": "MongoDB Connection String with Credentials",
            "severity": "critical",
            "confidence": "high",
            "description": "A MongoDB connection string with embedded credentials was found. This exposes database username and password.",
            "remediation": "Use environment variables for the connection string. Never hardcode MongoDB URIs with credentials in source code.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)mysql://[^:]+:[^@]+@''',
            "vulnerability": "MySQL Connection String with Credentials",
            "severity": "critical",
            "confidence": "high",
            "description": "A MySQL connection string with embedded credentials was found in the source code.",
            "remediation": "Use environment variables for database connection strings. Never hardcode credentials in source code.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)postgres(ql)?://[^:]+:[^@]+@''',
            "vulnerability": "PostgreSQL Connection String with Credentials",
            "severity": "critical",
            "confidence": "high",
            "description": "A PostgreSQL connection string with embedded credentials was found in the source code.",
            "remediation": "Use environment variables for database connection strings. Never hardcode credentials in source code.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}''',
            "vulnerability": "GitHub Token",
            "severity": "critical",
            "confidence": "high",
            "description": "A GitHub personal access token was detected. This token provides access to GitHub repositories and actions.",
            "remediation": "Revoke the token immediately in GitHub Settings > Developer Settings. Use GitHub Actions secrets or environment variables instead.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
        {
            "pattern": r'''(?i)sk-[A-Za-z0-9]{20,}''',
            "vulnerability": "Possible OpenAI/Stripe Secret Key",
            "severity": "critical",
            "confidence": "medium",
            "description": "A secret key matching the pattern of OpenAI or Stripe API keys was found. These keys provide access to paid services.",
            "remediation": "Verify and rotate the key immediately. Store API keys in environment variables or a secrets manager.",
            "owasp_ref": "A07:2021 - Identification and Authentication Failures",
            "cwe_id": "CWE-798",
        },
    ]

    def scan_file(self, file_path: str, content: str, language: str) -> List[Finding]:
        return self._search_patterns(
            self.PATTERNS, content, file_path, language,
            "Hardcoded Secret", "critical",
            "Hardcoded credential or secret detected in source code.",
            "Use environment variables or a secrets manager. Never commit secrets to source code.",
            "A07:2021 - Identification and Authentication Failures", "CWE-798",
        )
