from typing import List
from scanner.base import BaseScanner
from scanner.models import Finding


class InjectionScanner(BaseScanner):
    name = "InjectionScanner"
    category = "Injection"

    PYTHON_PATTERNS = [
        {
            "pattern": r'''execute\s*\(\s*["'].*%s''',
            "vulnerability": "SQL Injection (String Formatting)",
            "severity": "critical",
            "confidence": "high",
            "description": "SQL query constructed using string formatting with %s placeholder. This allows attackers to inject malicious SQL code.",
            "remediation": "Use parameterized queries: cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-89",
        },
        {
            "pattern": r'''execute\s*\(\s*f["']''',
            "vulnerability": "SQL Injection (f-string)",
            "severity": "critical",
            "confidence": "high",
            "description": "SQL query built using f-string interpolation. User input can alter the query structure, enabling SQL injection attacks.",
            "remediation": "Use parameterized queries or an ORM like SQLAlchemy instead of string interpolation.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-89",
        },
        {
            "pattern": r'''execute\s*\(.*\.format\s*\(''',
            "vulnerability": "SQL Injection (.format())",
            "severity": "critical",
            "confidence": "high",
            "description": "SQL query constructed using .format() method. This is vulnerable to SQL injection if any input is user-controlled.",
            "remediation": "Use parameterized queries: cursor.execute('SELECT * FROM users WHERE id = ?', (user_id,))",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-89",
        },
        {
            "pattern": r'''execute\s*\(.*\+\s*''',
            "vulnerability": "SQL Injection (String Concatenation)",
            "severity": "critical",
            "confidence": "medium",
            "description": "SQL query built using string concatenation. This is a common SQL injection vector.",
            "remediation": "Use parameterized queries or prepared statements instead of concatenating user input into SQL strings.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-89",
        },
        {
            "pattern": r'''os\.system\s*\(''',
            "vulnerability": "OS Command Injection",
            "severity": "critical",
            "confidence": "high",
            "description": "os.system() executes shell commands directly. If any part of the command contains user input, it enables command injection.",
            "remediation": "Use subprocess.run() with a list of arguments and shell=False. Never pass user input directly to system commands.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-78",
        },
        {
            "pattern": r'''os\.popen\s*\(''',
            "vulnerability": "OS Command Injection (popen)",
            "severity": "critical",
            "confidence": "high",
            "description": "os.popen() opens a pipe to a shell command. User-controlled input in the command string allows command injection.",
            "remediation": "Use subprocess.run() with shell=False and pass arguments as a list.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-78",
        },
        {
            "pattern": r'''subprocess\.call\s*\(.*shell\s*=\s*True''',
            "vulnerability": "Shell Injection (subprocess with shell=True)",
            "severity": "high",
            "confidence": "high",
            "description": "Using subprocess.call with shell=True makes the command vulnerable to shell injection if any arguments contain user input.",
            "remediation": "Set shell=False and pass command arguments as a list: subprocess.run(['ls', '-la'], shell=False)",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-78",
        },
        {
            "pattern": r'''subprocess\.\w+\s*\(.*shell\s*=\s*True''',
            "vulnerability": "Shell Injection (subprocess with shell=True)",
            "severity": "high",
            "confidence": "high",
            "description": "Using subprocess with shell=True enables shell injection attacks when user input is part of the command.",
            "remediation": "Use shell=False and pass arguments as a list to prevent shell metacharacter injection.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-78",
        },
        {
            "pattern": r'''eval\s*\(''',
            "vulnerability": "Code Injection (eval)",
            "severity": "critical",
            "confidence": "medium",
            "description": "eval() executes arbitrary Python code. If user input reaches eval(), attackers can execute any code on the server.",
            "remediation": "Avoid eval() entirely. Use ast.literal_eval() for safe parsing of Python literals, or redesign the logic.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-95",
        },
        {
            "pattern": r'''exec\s*\(''',
            "vulnerability": "Code Injection (exec)",
            "severity": "critical",
            "confidence": "medium",
            "description": "exec() executes arbitrary Python code. User-controlled input reaching exec() allows full remote code execution.",
            "remediation": "Remove exec() and use safe alternatives. If dynamic behavior is needed, use a whitelist-based approach.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-95",
        },
        {
            "pattern": r'''pickle\.loads?\s*\(''',
            "vulnerability": "Insecure Deserialization (pickle)",
            "severity": "critical",
            "confidence": "medium",
            "description": "pickle.load/loads can execute arbitrary code during deserialization. Untrusted data passed to pickle is a remote code execution risk.",
            "remediation": "Use JSON or other safe serialization formats. If pickle is required, only deserialize trusted data and use HMAC verification.",
            "owasp_ref": "A08:2021 - Software and Data Integrity Failures",
            "cwe_id": "CWE-502",
        },
        {
            "pattern": r'''yaml\.load\s*\([^)]*\)\s*(?!.*Loader)''',
            "vulnerability": "Unsafe YAML Deserialization",
            "severity": "high",
            "confidence": "medium",
            "description": "yaml.load() without a safe Loader can execute arbitrary Python objects. This is a deserialization vulnerability.",
            "remediation": "Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader) instead.",
            "owasp_ref": "A08:2021 - Software and Data Integrity Failures",
            "cwe_id": "CWE-502",
        },
        {
            "pattern": r'''__import__\s*\(''',
            "vulnerability": "Dynamic Import Injection",
            "severity": "high",
            "confidence": "medium",
            "description": "__import__() with user-controlled input can load arbitrary modules, potentially executing malicious code.",
            "remediation": "Use importlib.import_module() with a whitelist of allowed module names.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-95",
        },
    ]

    JS_PATTERNS = [
        {
            "pattern": r'''\beval\s*\(''',
            "vulnerability": "Code Injection (eval in JS)",
            "severity": "critical",
            "confidence": "medium",
            "description": "eval() executes arbitrary JavaScript. If user input reaches eval(), it enables cross-site scripting and code injection.",
            "remediation": "Avoid eval(). Use JSON.parse() for JSON data, or Function constructor with strict input validation.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-95",
        },
        {
            "pattern": r'''new\s+Function\s*\(''',
            "vulnerability": "Dynamic Code Execution (new Function)",
            "severity": "high",
            "confidence": "medium",
            "description": "new Function() creates functions from strings at runtime, similar to eval. User input in the string enables code injection.",
            "remediation": "Avoid creating functions from strings. Use predefined functions or a safe expression parser.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-95",
        },
        {
            "pattern": r'''setTimeout\s*\(\s*["'`][^"'`]*['"`]\s*,''',
            "vulnerability": "Code Injection (setTimeout with string)",
            "severity": "medium",
            "confidence": "medium",
            "description": "setTimeout with a string argument acts like eval. If the string contains user input, it enables code injection.",
            "remediation": "Pass a function reference to setTimeout instead of a string: setTimeout(myFunction, 1000)",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-95",
        },
        {
            "pattern": r'''setInterval\s*\(\s*["'`][^"'`]*['"`]\s*,''',
            "vulnerability": "Code Injection (setInterval with string)",
            "severity": "medium",
            "confidence": "medium",
            "description": "setInterval with a string argument acts like eval and can execute arbitrary code.",
            "remediation": "Pass a function reference instead of a string to setInterval.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-95",
        },
        {
            "pattern": r'''document\.write\s*\(''',
            "vulnerability": "DOM-based XSS (document.write)",
            "severity": "high",
            "confidence": "medium",
            "description": "document.write() can overwrite the page and inject scripts. If user input reaches document.write(), it enables XSS.",
            "remediation": "Use DOM manipulation methods like textContent or createElement instead of document.write().",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-79",
        },
        {
            "pattern": r'''(query|execute|run)\s*\(.*[\+].*req\.''',
            "vulnerability": "SQL Injection (Node.js)",
            "severity": "critical",
            "confidence": "high",
            "description": "SQL query constructed by concatenating request parameters. This is a direct SQL injection vulnerability.",
            "remediation": "Use parameterized queries: db.query('SELECT * FROM users WHERE id = ?', [req.params.id])",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-89",
        },
        {
            "pattern": r'''(query|execute|run)\s*\(\s*`.*\$\{''',
            "vulnerability": "SQL Injection (Template Literal)",
            "severity": "critical",
            "confidence": "high",
            "description": "SQL query built using template literals with embedded expressions. User input can alter the query structure.",
            "remediation": "Use parameterized queries with placeholders instead of template literals for SQL.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-89",
        },
        {
            "pattern": r'''child_process\.exec\s*\(''',
            "vulnerability": "Command Injection (Node.js)",
            "severity": "critical",
            "confidence": "high",
            "description": "child_process.exec() runs commands through a shell. User input in the command string enables command injection.",
            "remediation": "Use child_process.execFile() or child_process.spawn() with shell:false and argument arrays.",
            "owasp_ref": "A03:2021 - Injection",
            "cwe_id": "CWE-78",
        },
    ]

    def scan_file(self, file_path: str, content: str, language: str) -> List[Finding]:
        if language == "py":
            return self._search_patterns(
                self.PYTHON_PATTERNS, content, file_path, language,
                "Injection Vulnerability", "high",
                "Potential injection vulnerability detected.",
                "Use parameterized queries and safe APIs.",
                "A03:2021 - Injection", "CWE-89",
            )
        elif language in ("js", "jsx", "ts", "tsx"):
            return self._search_patterns(
                self.JS_PATTERNS, content, file_path, language,
                "Injection Vulnerability", "high",
                "Potential injection vulnerability detected.",
                "Use safe APIs and parameterized queries.",
                "A03:2021 - Injection", "CWE-89",
            )
        return []
